### ISSUE TITLE
SyntaxError: Invalid shorthand property initializer

### ISSUE THREAD

**Issue by kimpellikaan** [theburningmonk/appsyncmasterclass-backend#1]
https://github.com/theburningmonk/appsyncmasterclass-backend/blob/92e9cbad732060b4363246c19db05029517f9934/lib/constants.js#L8

```
const DynamoDB = {
  MAX_BATCH_SIZE : 25
}
```

Please change the = sign to :

**Comment by theburningmonk** [comment]
That's one of the bugs that will be caught and fixed in the next lesson I'm recording (integration testing the distribute-tweets function)

**Comment by kimpellikaan** [comment]
Lol :) 👍

**Comment by theburningmonk** [comment]
haha, it wasn't a deliberate plant, I only noticed after editing the video, but that's the value of integration tests - so you catch code bugs before you deploy :-P
